
# list all script files
is_dev: true

component_js:
  - components/classie/classie.js
  - components/eventEmitter/EventEmitter.js
  - components/eventie/eventie.js
  - components/doc-listener/doc-listener.js
  - components/get-style-property/get-style-property.js
  - components/get-size/get-size.js
  - components/draggabilly/draggabilly.js
  - components/matches-selector/matches-selector.js
  - components/packery/js/rect.js
  - components/packery/js/packer.js
  - components/packery/js/item.js
  - components/packery/js/packery.js
